#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capaDatos.Persistencia
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Db_BancaSeguro")]
	public partial class Db_BancaSeguroAPIDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertTD_TenantCliente(TD_TenantCliente instance);
    partial void UpdateTD_TenantCliente(TD_TenantCliente instance);
    partial void DeleteTD_TenantCliente(TD_TenantCliente instance);
    partial void InsertTM_Cliente(TM_Cliente instance);
    partial void UpdateTM_Cliente(TM_Cliente instance);
    partial void DeleteTM_Cliente(TM_Cliente instance);
    partial void InsertTM_Tenant(TM_Tenant instance);
    partial void UpdateTM_Tenant(TM_Tenant instance);
    partial void DeleteTM_Tenant(TM_Tenant instance);
    #endregion
		
		public Db_BancaSeguroAPIDataContext() : 
				base(global::capaDatos.Properties.Settings.Default.Db_BancaSeguroConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Db_BancaSeguroAPIDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_BancaSeguroAPIDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_BancaSeguroAPIDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Db_BancaSeguroAPIDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<TD_TenantCliente> TD_TenantClientes
		{
			get
			{
				return this.GetTable<TD_TenantCliente>();
			}
		}
		
		public System.Data.Linq.Table<TM_Cliente> TM_Clientes
		{
			get
			{
				return this.GetTable<TM_Cliente>();
			}
		}
		
		public System.Data.Linq.Table<TM_Tenant> TM_Tenants
		{
			get
			{
				return this.GetTable<TM_Tenant>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TD_TenantClientes")]
	public partial class TD_TenantCliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTenantClientes;
		
		private int _idClientes;
		
		private int _idTenant;
		
		private System.DateTime _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private System.Nullable<System.DateTime> _FechaEliminacion;
		
		private string _CreadoPor;
		
		private string _ModificadoPor;
		
		private string _EliminadoPor;
		
		private bool _flagActivo;
		
		private EntityRef<TM_Cliente> _TM_Cliente;
		
		private EntityRef<TM_Tenant> _TM_Tenant;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTenantClientesChanging(int value);
    partial void OnidTenantClientesChanged();
    partial void OnidClientesChanging(int value);
    partial void OnidClientesChanged();
    partial void OnidTenantChanging(int value);
    partial void OnidTenantChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificacionChanged();
    partial void OnFechaEliminacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEliminacionChanged();
    partial void OnCreadoPorChanging(string value);
    partial void OnCreadoPorChanged();
    partial void OnModificadoPorChanging(string value);
    partial void OnModificadoPorChanged();
    partial void OnEliminadoPorChanging(string value);
    partial void OnEliminadoPorChanged();
    partial void OnflagActivoChanging(bool value);
    partial void OnflagActivoChanged();
    #endregion
		
		public TD_TenantCliente()
		{
			this._TM_Cliente = default(EntityRef<TM_Cliente>);
			this._TM_Tenant = default(EntityRef<TM_Tenant>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTenantClientes", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTenantClientes
		{
			get
			{
				return this._idTenantClientes;
			}
			set
			{
				if ((this._idTenantClientes != value))
				{
					this.OnidTenantClientesChanging(value);
					this.SendPropertyChanging();
					this._idTenantClientes = value;
					this.SendPropertyChanged("idTenantClientes");
					this.OnidTenantClientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClientes", DbType="Int NOT NULL")]
		public int idClientes
		{
			get
			{
				return this._idClientes;
			}
			set
			{
				if ((this._idClientes != value))
				{
					if (this._TM_Cliente.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidClientesChanging(value);
					this.SendPropertyChanging();
					this._idClientes = value;
					this.SendPropertyChanged("idClientes");
					this.OnidClientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTenant", DbType="Int NOT NULL")]
		public int idTenant
		{
			get
			{
				return this._idTenant;
			}
			set
			{
				if ((this._idTenant != value))
				{
					if (this._TM_Tenant.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnidTenantChanging(value);
					this.SendPropertyChanging();
					this._idTenant = value;
					this.SendPropertyChanged("idTenant");
					this.OnidTenantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEliminacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaEliminacion
		{
			get
			{
				return this._FechaEliminacion;
			}
			set
			{
				if ((this._FechaEliminacion != value))
				{
					this.OnFechaEliminacionChanging(value);
					this.SendPropertyChanging();
					this._FechaEliminacion = value;
					this.SendPropertyChanged("FechaEliminacion");
					this.OnFechaEliminacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this.OnCreadoPorChanging(value);
					this.SendPropertyChanging();
					this._CreadoPor = value;
					this.SendPropertyChanged("CreadoPor");
					this.OnCreadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(MAX)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this.OnModificadoPorChanging(value);
					this.SendPropertyChanging();
					this._ModificadoPor = value;
					this.SendPropertyChanged("ModificadoPor");
					this.OnModificadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EliminadoPor", DbType="VarChar(MAX)")]
		public string EliminadoPor
		{
			get
			{
				return this._EliminadoPor;
			}
			set
			{
				if ((this._EliminadoPor != value))
				{
					this.OnEliminadoPorChanging(value);
					this.SendPropertyChanging();
					this._EliminadoPor = value;
					this.SendPropertyChanged("EliminadoPor");
					this.OnEliminadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flagActivo", DbType="Bit NOT NULL")]
		public bool flagActivo
		{
			get
			{
				return this._flagActivo;
			}
			set
			{
				if ((this._flagActivo != value))
				{
					this.OnflagActivoChanging(value);
					this.SendPropertyChanging();
					this._flagActivo = value;
					this.SendPropertyChanged("flagActivo");
					this.OnflagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Cliente_TD_TenantCliente", Storage="_TM_Cliente", ThisKey="idClientes", OtherKey="idClientes", IsForeignKey=true)]
		public TM_Cliente TM_Cliente
		{
			get
			{
				return this._TM_Cliente.Entity;
			}
			set
			{
				TM_Cliente previousValue = this._TM_Cliente.Entity;
				if (((previousValue != value) 
							|| (this._TM_Cliente.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Cliente.Entity = null;
						previousValue.TD_TenantClientes.Remove(this);
					}
					this._TM_Cliente.Entity = value;
					if ((value != null))
					{
						value.TD_TenantClientes.Add(this);
						this._idClientes = value.idClientes;
					}
					else
					{
						this._idClientes = default(int);
					}
					this.SendPropertyChanged("TM_Cliente");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Tenant_TD_TenantCliente", Storage="_TM_Tenant", ThisKey="idTenant", OtherKey="idTenant", IsForeignKey=true)]
		public TM_Tenant TM_Tenant
		{
			get
			{
				return this._TM_Tenant.Entity;
			}
			set
			{
				TM_Tenant previousValue = this._TM_Tenant.Entity;
				if (((previousValue != value) 
							|| (this._TM_Tenant.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TM_Tenant.Entity = null;
						previousValue.TD_TenantClientes.Remove(this);
					}
					this._TM_Tenant.Entity = value;
					if ((value != null))
					{
						value.TD_TenantClientes.Add(this);
						this._idTenant = value.idTenant;
					}
					else
					{
						this._idTenant = default(int);
					}
					this.SendPropertyChanged("TM_Tenant");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Clientes")]
	public partial class TM_Cliente : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idClientes;
		
		private string _Nombre;
		
		private string _Identificacion_rnc_cedula;
		
		private System.DateTime _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private System.Nullable<System.DateTime> _FechaEliminacion;
		
		private string _CreadoPor;
		
		private string _ModificadoPor;
		
		private string _EliminadoPor;
		
		private bool _flagActivo;
		
		private EntitySet<TD_TenantCliente> _TD_TenantClientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidClientesChanging(int value);
    partial void OnidClientesChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnIdentificacion_rnc_cedulaChanging(string value);
    partial void OnIdentificacion_rnc_cedulaChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificacionChanged();
    partial void OnFechaEliminacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEliminacionChanged();
    partial void OnCreadoPorChanging(string value);
    partial void OnCreadoPorChanged();
    partial void OnModificadoPorChanging(string value);
    partial void OnModificadoPorChanged();
    partial void OnEliminadoPorChanging(string value);
    partial void OnEliminadoPorChanged();
    partial void OnflagActivoChanging(bool value);
    partial void OnflagActivoChanged();
    #endregion
		
		public TM_Cliente()
		{
			this._TD_TenantClientes = new EntitySet<TD_TenantCliente>(new Action<TD_TenantCliente>(this.attach_TD_TenantClientes), new Action<TD_TenantCliente>(this.detach_TD_TenantClientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idClientes", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idClientes
		{
			get
			{
				return this._idClientes;
			}
			set
			{
				if ((this._idClientes != value))
				{
					this.OnidClientesChanging(value);
					this.SendPropertyChanging();
					this._idClientes = value;
					this.SendPropertyChanged("idClientes");
					this.OnidClientesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(50)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificacion_rnc_cedula", DbType="NVarChar(50)")]
		public string Identificacion_rnc_cedula
		{
			get
			{
				return this._Identificacion_rnc_cedula;
			}
			set
			{
				if ((this._Identificacion_rnc_cedula != value))
				{
					this.OnIdentificacion_rnc_cedulaChanging(value);
					this.SendPropertyChanging();
					this._Identificacion_rnc_cedula = value;
					this.SendPropertyChanged("Identificacion_rnc_cedula");
					this.OnIdentificacion_rnc_cedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEliminacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaEliminacion
		{
			get
			{
				return this._FechaEliminacion;
			}
			set
			{
				if ((this._FechaEliminacion != value))
				{
					this.OnFechaEliminacionChanging(value);
					this.SendPropertyChanging();
					this._FechaEliminacion = value;
					this.SendPropertyChanged("FechaEliminacion");
					this.OnFechaEliminacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this.OnCreadoPorChanging(value);
					this.SendPropertyChanging();
					this._CreadoPor = value;
					this.SendPropertyChanged("CreadoPor");
					this.OnCreadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(MAX)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this.OnModificadoPorChanging(value);
					this.SendPropertyChanging();
					this._ModificadoPor = value;
					this.SendPropertyChanged("ModificadoPor");
					this.OnModificadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EliminadoPor", DbType="VarChar(MAX)")]
		public string EliminadoPor
		{
			get
			{
				return this._EliminadoPor;
			}
			set
			{
				if ((this._EliminadoPor != value))
				{
					this.OnEliminadoPorChanging(value);
					this.SendPropertyChanging();
					this._EliminadoPor = value;
					this.SendPropertyChanged("EliminadoPor");
					this.OnEliminadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flagActivo", DbType="Bit NOT NULL")]
		public bool flagActivo
		{
			get
			{
				return this._flagActivo;
			}
			set
			{
				if ((this._flagActivo != value))
				{
					this.OnflagActivoChanging(value);
					this.SendPropertyChanging();
					this._flagActivo = value;
					this.SendPropertyChanged("flagActivo");
					this.OnflagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Cliente_TD_TenantCliente", Storage="_TD_TenantClientes", ThisKey="idClientes", OtherKey="idClientes")]
		public EntitySet<TD_TenantCliente> TD_TenantClientes
		{
			get
			{
				return this._TD_TenantClientes;
			}
			set
			{
				this._TD_TenantClientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_TenantClientes(TD_TenantCliente entity)
		{
			this.SendPropertyChanging();
			entity.TM_Cliente = this;
		}
		
		private void detach_TD_TenantClientes(TD_TenantCliente entity)
		{
			this.SendPropertyChanging();
			entity.TM_Cliente = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TM_Tenant")]
	public partial class TM_Tenant : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _idTenant;
		
		private string _Descripcion;
		
		private string _IdentificadorIP;
		
		private string _ConexionString;
		
		private System.DateTime _FechaCreacion;
		
		private System.Nullable<System.DateTime> _FechaModificacion;
		
		private System.Nullable<System.DateTime> _FechaEliminacion;
		
		private string _CreadoPor;
		
		private string _ModificadoPor;
		
		private string _EliminadoPor;
		
		private bool _flagActivo;
		
		private EntitySet<TD_TenantCliente> _TD_TenantClientes;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidTenantChanging(int value);
    partial void OnidTenantChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnIdentificadorIPChanging(string value);
    partial void OnIdentificadorIPChanged();
    partial void OnConexionStringChanging(string value);
    partial void OnConexionStringChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnFechaModificacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaModificacionChanged();
    partial void OnFechaEliminacionChanging(System.Nullable<System.DateTime> value);
    partial void OnFechaEliminacionChanged();
    partial void OnCreadoPorChanging(string value);
    partial void OnCreadoPorChanged();
    partial void OnModificadoPorChanging(string value);
    partial void OnModificadoPorChanged();
    partial void OnEliminadoPorChanging(string value);
    partial void OnEliminadoPorChanged();
    partial void OnflagActivoChanging(bool value);
    partial void OnflagActivoChanged();
    #endregion
		
		public TM_Tenant()
		{
			this._TD_TenantClientes = new EntitySet<TD_TenantCliente>(new Action<TD_TenantCliente>(this.attach_TD_TenantClientes), new Action<TD_TenantCliente>(this.detach_TD_TenantClientes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idTenant", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int idTenant
		{
			get
			{
				return this._idTenant;
			}
			set
			{
				if ((this._idTenant != value))
				{
					this.OnidTenantChanging(value);
					this.SendPropertyChanging();
					this._idTenant = value;
					this.SendPropertyChanged("idTenant");
					this.OnidTenantChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(50)")]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdentificadorIP", DbType="VarChar(MAX)")]
		public string IdentificadorIP
		{
			get
			{
				return this._IdentificadorIP;
			}
			set
			{
				if ((this._IdentificadorIP != value))
				{
					this.OnIdentificadorIPChanging(value);
					this.SendPropertyChanging();
					this._IdentificadorIP = value;
					this.SendPropertyChanged("IdentificadorIP");
					this.OnIdentificadorIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ConexionString", DbType="VarChar(MAX)")]
		public string ConexionString
		{
			get
			{
				return this._ConexionString;
			}
			set
			{
				if ((this._ConexionString != value))
				{
					this.OnConexionStringChanging(value);
					this.SendPropertyChanging();
					this._ConexionString = value;
					this.SendPropertyChanged("ConexionString");
					this.OnConexionStringChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaModificacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaModificacion
		{
			get
			{
				return this._FechaModificacion;
			}
			set
			{
				if ((this._FechaModificacion != value))
				{
					this.OnFechaModificacionChanging(value);
					this.SendPropertyChanging();
					this._FechaModificacion = value;
					this.SendPropertyChanged("FechaModificacion");
					this.OnFechaModificacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaEliminacion", DbType="DateTime")]
		public System.Nullable<System.DateTime> FechaEliminacion
		{
			get
			{
				return this._FechaEliminacion;
			}
			set
			{
				if ((this._FechaEliminacion != value))
				{
					this.OnFechaEliminacionChanging(value);
					this.SendPropertyChanging();
					this._FechaEliminacion = value;
					this.SendPropertyChanged("FechaEliminacion");
					this.OnFechaEliminacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CreadoPor", DbType="VarChar(MAX) NOT NULL", CanBeNull=false)]
		public string CreadoPor
		{
			get
			{
				return this._CreadoPor;
			}
			set
			{
				if ((this._CreadoPor != value))
				{
					this.OnCreadoPorChanging(value);
					this.SendPropertyChanging();
					this._CreadoPor = value;
					this.SendPropertyChanged("CreadoPor");
					this.OnCreadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ModificadoPor", DbType="VarChar(MAX)")]
		public string ModificadoPor
		{
			get
			{
				return this._ModificadoPor;
			}
			set
			{
				if ((this._ModificadoPor != value))
				{
					this.OnModificadoPorChanging(value);
					this.SendPropertyChanging();
					this._ModificadoPor = value;
					this.SendPropertyChanged("ModificadoPor");
					this.OnModificadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EliminadoPor", DbType="VarChar(MAX)")]
		public string EliminadoPor
		{
			get
			{
				return this._EliminadoPor;
			}
			set
			{
				if ((this._EliminadoPor != value))
				{
					this.OnEliminadoPorChanging(value);
					this.SendPropertyChanging();
					this._EliminadoPor = value;
					this.SendPropertyChanged("EliminadoPor");
					this.OnEliminadoPorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flagActivo", DbType="Bit NOT NULL")]
		public bool flagActivo
		{
			get
			{
				return this._flagActivo;
			}
			set
			{
				if ((this._flagActivo != value))
				{
					this.OnflagActivoChanging(value);
					this.SendPropertyChanging();
					this._flagActivo = value;
					this.SendPropertyChanged("flagActivo");
					this.OnflagActivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TM_Tenant_TD_TenantCliente", Storage="_TD_TenantClientes", ThisKey="idTenant", OtherKey="idTenant")]
		public EntitySet<TD_TenantCliente> TD_TenantClientes
		{
			get
			{
				return this._TD_TenantClientes;
			}
			set
			{
				this._TD_TenantClientes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_TD_TenantClientes(TD_TenantCliente entity)
		{
			this.SendPropertyChanging();
			entity.TM_Tenant = this;
		}
		
		private void detach_TD_TenantClientes(TD_TenantCliente entity)
		{
			this.SendPropertyChanging();
			entity.TM_Tenant = null;
		}
	}
}
#pragma warning restore 1591
